environment:
  matrix:
    - PLATFORM: x64
      GENERATOR: "Visual Studio 16 2019"
      BUILD_TYPE: Release

cache:
  - C:\petzone\llvm\llvm-prebuilt\llvmorg-11.1.0-msbuild-vs2019-x64-rel
  - llvm-project.git-11.1.0\build

before_build:
  - ps: |
      git clone https://github.com/llvm/llvm-project.git llvm-project.git-11.1.0
      cd llvm-project.git-11.1.0
      git checkout llvmorg-11.1.0

build_script:
  - ps: |
      mkdir llvm-project.git-11.1.0\build
      cd llvm-project.git-11.1.0\build
      cmake -G "%GENERATOR%" -A %PLATFORM% ^
        -DLLVM_ENABLE_ABI_BREAKING_CHECKS=0 ^
        -DLLVM_USE_LINKER=lld ^
        -DLLVM_TARGETS_TO_BUILD="X86" ^
        -DLLVM_ENABLE_PROJECTS="clang;llvm" ^
        -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ^
        -DCMAKE_INSTALL_PREFIX="C:\petzone\llvm\llvm-prebuilt\llvmorg-11.1.0-msbuild-vs2019-x64-rel" ^
        ..\llvm
      cmake --build . --config %BUILD_TYPE%
      cmake -P cmake_install.cmake

after_build:
  - ps: |
      git clone https://github.com/dougpuob/hello-clangtool.git hello-clangtool.git
      cd hello-clangtool.git\build-with-prebuilt\build
      cmake .. -DLLVM_INSTALL_DIR="C:\petzone\llvm\llvm-prebuilt\llvmorg-11.1.0-msbuild-vs2019-x64-rel"
      cmake --build . --config %BUILD_TYPE%
