environment:
  BUILD_TYPE: Release

branches:
  only:
    - main

image:
  os: Visual Studio 2019

cache:
  - llvm-project.git-11.1.0/build => llvm-build-{platform}-{branch}
  
init:
  - git config --global core.autocrlf true

build_script:
  - mkdir llvm-project.git-11.1.0
  - cd llvm-project.git-11.1.0
  - git clone https://github.com/llvm/llvm-project.git .
  - git checkout llvmorg-11.1.0
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 17 2022" -A x64 `
      -DLLVM_ENABLE_ABI_BREAKING_CHECKS=0 `
      -DLLVM_USE_LINKER=lld `
      -DLLVM_TARGETS_TO_BUILD="X86" `
      -DLLVM_ENABLE_PROJECTS="clang;llvm" `
      -DCMAKE_BUILD_TYPE=Release `
      -DCMAKE_INSTALL_PREFIX="C:\petzone\llvm\llvm-prebuilt\llvmorg-11.1.0-msbuild-vs2019-x64-rel" `
      ../llvm
  - cmake --build . --config Release
  - cmake -P cmake_install.cmake
