version: 1.0.{build}

image: Visual Studio 2019

environment:
  matrix:
    - LLVM_VERSION: "16"

install:
  - cmake --version
  - choco install llvm --version %LLVM_VERSION%

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config Release

test_script:
  - ctest --output-on-failure

artifacts:
  - path: build\bin\Release
    name: Release
