version: 1.0.{build}

environment:
  matrix:
    - LLVM_DIR: "C:\\Program Files\\LLVM\\lib\\cmake\\llvm"
   

branches:
  only:
    - main

image: Visual Studio 2022

build_script:
  - ps: |
      dir "C:\Program Files\LLVM\lib\cmake\llvm"
      dir "C:\Program Files\LLVM\bin"
      # Build script commands
      mkdir hello-clangtool.git
      cd hello-clangtool.git
      git clone https://github.com./dougpuob/hello-clangtool.git .
      cd build-with-prebuilt
      mkdir build
      cd build
      mklink "llvm-config.cmake" "LLVMConfigExtensions.cmake"
      cmake -G "Visual Studio 17 2022" -A x64 .. -DLLVM_INSTALL_DIR="C:\\Program Files\\LLVM"
      cmake --build . --config Release
