name: llvm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: test
      run: |
            mkdir hello-clangtool.git
            cd hello-clangtool.git
            git clone https://github.com./dougpuob/hello-clangtool.git .
            cd build-with-prebuilt
            mkdir build
            cd build
            $env:LLVM_DIR = "C:\Program Files\LLVM\lib\cmake\llvm"
            $env:CMAKE_PREFIX_PATH = "C:\Program Files\LLVM"
            cmake -G "Visual Studio 17 2022" -A x64 .. -DLLVM_INSTALL_DIR="C:\Program Files\LLVM\lib\cmake\llvm" -DLLVM_CONFIG_FILE="LLVMConfigExtensions.cmake"
            cmake --build . --config Release
